apiVersion: apps/v1
kind: Deployment
metadata:
  name: hookabook-audiobook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hookabook-audiobook
  template:
    metadata:
      labels:
        app: hookabook-audiobook
    spec:
      containers:
        - image: cedeladela/hookabook:audiobook-microservice_2024-01-02-17-18-35
          name: hookabook-audiobook
          env:
            - name: DATASOURCE_CONNECTION_URL
              value: jdbc:postgresql://cedeladela.crabdance.com:64432/hookabook
            - name: DATASOURCE_USERNAME
              value: hookabook
            - name: DATASOURCE_PASSWORD
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: datasource-password
                  key: password
            - name: MINIO_ENDPOINT
              value: http://cedeladela.crabdance.com:64000
            - name: MINIO_ACCESS_KEY
              value: PP8VR990kZYk4YPNuinq
            - name: MINIO_SECRET_KEY
              value: x2zMzEG9KqivXd1rTPxmuxh3vZ6I3vW0iI49pyKP
            - name: MINIO_BUCKET_NAME
              value: hookabook
          ports:
            - containerPort: 8081
              name: server
          livenessProbe:
            httpGet:
              path: /health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: hookabook-audiobook
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: hookabook-audiobook







